package com.admom.mygreendaotest;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yjlw.ddms.homeentity.entity.Note;
import com.yjlw.ddms.homeentity.entity.ShoppingCartData;

import com.admom.mygreendaotest.NoteDao;
import com.admom.mygreendaotest.ShoppingCartDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig noteDaoConfig;
    private final DaoConfig shoppingCartDataDaoConfig;

    private final NoteDao noteDao;
    private final ShoppingCartDataDao shoppingCartDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        shoppingCartDataDaoConfig = daoConfigMap.get(ShoppingCartDataDao.class).clone();
        shoppingCartDataDaoConfig.initIdentityScope(type);

        noteDao = new NoteDao(noteDaoConfig, this);
        shoppingCartDataDao = new ShoppingCartDataDao(shoppingCartDataDaoConfig, this);

        registerDao(Note.class, noteDao);
        registerDao(ShoppingCartData.class, shoppingCartDataDao);
    }
    
    public void clear() {
        noteDaoConfig.clearIdentityScope();
        shoppingCartDataDaoConfig.clearIdentityScope();
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public ShoppingCartDataDao getShoppingCartDataDao() {
        return shoppingCartDataDao;
    }

}
