package com.admom.mygreendaotest;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SHOPPING_CART_DATA.
 */
public class ShoppingCartData {

    private Long id;
    /** Not-null value. */
    private String StoreId;
    private String StoreLogo;
    private String StoreName;
    private String CoverUrl;
    private String DealPrice;
    private String GoodsId;
    private String GoodsNum;
    private String Price;
    private String Title;

    public ShoppingCartData() {
    }

    public ShoppingCartData(Long id) {
        this.id = id;
    }

    public ShoppingCartData(Long id, String StoreId, String StoreLogo, String StoreName, String CoverUrl, String DealPrice, String GoodsId, String GoodsNum, String Price, String Title) {
        this.id = id;
        this.StoreId = StoreId;
        this.StoreLogo = StoreLogo;
        this.StoreName = StoreName;
        this.CoverUrl = CoverUrl;
        this.DealPrice = DealPrice;
        this.GoodsId = GoodsId;
        this.GoodsNum = GoodsNum;
        this.Price = Price;
        this.Title = Title;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getStoreId() {
        return StoreId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStoreId(String StoreId) {
        this.StoreId = StoreId;
    }

    public String getStoreLogo() {
        return StoreLogo;
    }

    public void setStoreLogo(String StoreLogo) {
        this.StoreLogo = StoreLogo;
    }

    public String getStoreName() {
        return StoreName;
    }

    public void setStoreName(String StoreName) {
        this.StoreName = StoreName;
    }

    public String getCoverUrl() {
        return CoverUrl;
    }

    public void setCoverUrl(String CoverUrl) {
        this.CoverUrl = CoverUrl;
    }

    public String getDealPrice() {
        return DealPrice;
    }

    public void setDealPrice(String DealPrice) {
        this.DealPrice = DealPrice;
    }

    public String getGoodsId() {
        return GoodsId;
    }

    public void setGoodsId(String GoodsId) {
        this.GoodsId = GoodsId;
    }

    public String getGoodsNum() {
        return GoodsNum;
    }

    public void setGoodsNum(String GoodsNum) {
        this.GoodsNum = GoodsNum;
    }

    public String getPrice() {
        return Price;
    }

    public void setPrice(String Price) {
        this.Price = Price;
    }

    public String getTitle() {
        return Title;
    }

    public void setTitle(String Title) {
        this.Title = Title;
    }

}
